COMMANDS = ["qlist"]
DESCRIPTION = "Quick list — symbols, currencies, units, countries"

DATA = {
"countries": [
	("🇦🇺", "AU", "Австралия", "Australia"),
	("🇦🇹", "AT", "Австрия", "Austria"),
	("🇦🇿", "AZ", "Азербайджан", "Azerbaijan"),
	("🇦🇱", "AL", "Албания", "Albania"),
	("🇩🇿", "DZ", "Алжир", "Algeria"),
	("🇦🇴", "AO", "Ангола", "Angola"),
	("🇦🇩", "AD", "Андорра", "Andorra"),
	("🇦🇷", "AR", "Аргентина", "Argentina"),
	("🇦🇲", "AM", "Армения", "Armenia"),
	("🇦🇫", "AF", "Афганистан", "Afghanistan"),
	("🇧🇸", "BS", "Багамы", "Bahamas"),
	("🇧🇩", "BD", "Бангладеш", "Bangladesh"),
	("🇧🇧", "BB", "Барбадос", "Barbados"),
	("🇧🇭", "BH", "Бахрейн", "Bahrain"),
	("🇧🇾", "BY", "Беларусь", "Belarus"),
	("🇧🇿", "BZ", "Белиз", "Belize"),
	("🇧🇪", "BE", "Бельгия", "Belgium"),
	("🇧🇯", "BJ", "Бенин", "Benin"),
	("🇧🇬", "BG", "Болгария", "Bulgaria"),
	("🇧🇴", "BO", "Боливия", "Bolivia"),
	("🇧🇦", "BA", "Босния и Герцеговина", "Bosnia and Herzegovina"),
	("🇧🇼", "BW", "Ботсвана", "Botswana"),
	("🇧🇷", "BR", "Бразилия", "Brazil"),
	("🇧🇳", "BN", "Бруней", "Brunei"),
	("🇧🇫", "BF", "Буркина-Фасо", "Burkina Faso"),
	("🇧🇮", "BI", "Бурунди", "Burundi"),
	("🇧🇹", "BT", "Бутан", "Bhutan"),
	("🇻🇺", "VU", "Вануату", "Vanuatu"),
	("🇻🇦", "VA", "Ватикан", "Vatican"),
	("🇬🇧", "GB", "Великобритания", "United Kingdom"),
	("🇭🇺", "HU", "Венгрия", "Hungary"),
	("🇻🇪", "VE", "Венесуэла", "Venezuela"),
	("🇻🇳", "VN", "Вьетнам", "Vietnam"),
	("🇬🇦", "GA", "Габон", "Gabon"),
	("🇭🇹", "HT", "Гаити", "Haiti"),
	("🇬🇾", "GY", "Гайана", "Guyana"),
	("🇬🇲", "GM", "Гамбия", "Gambia"),
	("🇬🇭", "GH", "Гана", "Ghana"),
	("🇬🇹", "GT", "Гватемала", "Guatemala"),
	("🇬🇳", "GN", "Гвинея", "Guinea"),
	("🇬🇼", "GW", "Гвинея-Бисау", "Guinea-Bissau"),
	("🇩🇪", "DE", "Германия", "Germany"),
	("🇭🇳", "HN", "Гондурас", "Honduras"),
	("🇬🇩", "GD", "Гренада", "Grenada"),
	("🇬🇷", "GR", "Греция", "Greece"),
	("🇬🇪", "GE", "Грузия", "Georgia"),
	("🇩🇰", "DK", "Дания", "Denmark"),
	("🇩🇯", "DJ", "Джибути", "Djibouti"),
	("🇩🇲", "DM", "Доминика", "Dominica"),
	("🇩🇴", "DO", "Доминикана", "Dominican Republic"),
	("🇪🇬", "EG", "Египет", "Egypt"),
	("🇿🇲", "ZM", "Замбия", "Zambia"),
	("🇿🇼", "ZW", "Зимбабве", "Zimbabwe"),
	("🇮🇱", "IL", "Израиль", "Israel"),
	("🇮🇳", "IN", "Индия", "India"),
	("🇮🇩", "ID", "Индонезия", "Indonesia"),
	("🇯🇴", "JO", "Иордания", "Jordan"),
	("🇮🇶", "IQ", "Ирак", "Iraq"),
	("🇮🇷", "IR", "Иран", "Iran"),
	("🇮🇪", "IE", "Ирландия", "Ireland"),
	("🇮🇸", "IS", "Исландия", "Iceland"),
	("🇪🇸", "ES", "Испания", "Spain"),
	("🇮🇹", "IT", "Италия", "Italy"),
	("🇾🇪", "YE", "Йемен", "Yemen"),
	("🇰🇿", "KZ", "Казахстан", "Kazakhstan"),
	("🇰🇭", "KH", "Камбоджа", "Cambodia"),
	("🇨🇲", "CM", "Камерун", "Cameroon"),
	("🇨🇦", "CA", "Канада", "Canada"),
	("🇶🇦", "QA", "Катар", "Qatar"),
	("🇰🇪", "KE", "Кения", "Kenya"),
	("🇨🇾", "CY", "Кипр", "Cyprus"),
	("🇰🇬", "KG", "Киргизия", "Kyrgyzstan"),
	("🇨🇳", "CN", "Китай", "China"),
	("🇨🇴", "CO", "Колумбия", "Colombia"),
	("🇰🇲", "KM", "Коморы", "Comoros"),
	("🇨🇬", "CG", "Конго", "Congo"),
	("🇰🇵", "KP", "КНДР", "North Korea"),
	("🇰🇷", "KR", "Южная Корея", "South Korea"),
	("🇨🇷", "CR", "Коста-Рика", "Costa Rica"),
	("🇨🇺", "CU", "Куба", "Cuba"),
	("🇰🇼", "KW", "Кувейт", "Kuwait"),
	("🇱🇦", "LA", "Лаос", "Laos"),
	("🇱🇻", "LV", "Латвия", "Latvia"),
	("🇱🇸", "LS", "Лесото", "Lesotho"),
	("🇱🇷", "LR", "Либерия", "Liberia"),
	("🇱🇧", "LB", "Ливан", "Lebanon"),
	("🇱🇾", "LY", "Ливия", "Libya"),
	("🇱🇹", "LT", "Литва", "Lithuania"),
	("🇱🇮", "LI", "Лихтенштейн", "Liechtenstein"),
	("🇱🇺", "LU", "Люксембург", "Luxembourg"),
	("🇲🇺", "MU", "Маврикий", "Mauritius"),
	("🇲🇷", "MR", "Мавритания", "Mauritania"),
	("🇲🇬", "MG", "Мадагаскар", "Madagascar"),
	("🇲🇰", "MK", "Северная Македония", "North Macedonia"),
	("🇲🇼", "MW", "Малави", "Malawi"),
	("🇲🇾", "MY", "Малайзия", "Malaysia"),
	("🇲🇱", "ML", "Мали", "Mali"),
	("🇲🇻", "MV", "Мальдивы", "Maldives"),
	("🇲🇹", "MT", "Мальта", "Malta"),
	("🇲🇦", "MA", "Марокко", "Morocco"),
	("🇲🇽", "MX", "Мексика", "Mexico"),
	("🇲🇿", "MZ", "Мозамбик", "Mozambique"),
	("🇲🇩", "MD", "Молдова", "Moldova"),
	("🇲🇨", "MC", "Монако", "Monaco"),
	("🇲🇳", "MN", "Монголия", "Mongolia"),
	("🇲🇲", "MM", "Мьянма", "Myanmar"),
	("🇳🇦", "NA", "Намибия", "Namibia"),
	("🇳🇷", "NR", "Науру", "Nauru"),
	("🇳🇵", "NP", "Непал", "Nepal"),
	("🇳🇪", "NE", "Нигер", "Niger"),
	("🇳🇬", "NG", "Нигерия", "Nigeria"),
	("🇳🇱", "NL", "Нидерланды", "Netherlands"),
	("🇳🇮", "NI", "Никарагуа", "Nicaragua"),
	("🇳🇿", "NZ", "Новая Зеландия", "New Zealand"),
	("🇳🇴", "NO", "Норвегия", "Norway"),
	("🇦🇪", "AE", "ОАЭ", "United Arab Emirates"),
	("🇴🇲", "OM", "Оман", "Oman"),
	("🇵🇰", "PK", "Пакистан", "Pakistan"),
	("🇵🇼", "PW", "Палау", "Palau"),
	("🇵🇦", "PA", "Панама", "Panama"),
	("🇵🇬", "PG", "Папуа — Новая Гвинея", "Papua New Guinea"),
	("🇵🇾", "PY", "Парагвай", "Paraguay"),
	("🇵🇪", "PE", "Перу", "Peru"),
	("🇵🇱", "PL", "Польша", "Poland"),
	("🇵🇹", "PT", "Португалия", "Portugal"),
	("🇷🇺", "RU", "Россия", "Russia"),
	("🇷🇼", "RW", "Руанда", "Rwanda"),
	("🇷🇴", "RO", "Румыния", "Romania"),
	("🇸🇻", "SV", "Сальвадор", "El Salvador"),
	("🇼🇸", "WS", "Самоа", "Samoa"),
	("🇸🇲", "SM", "Сан-Марино", "San Marino"),
	("🇸🇹", "ST", "Сан-Томе и Принсипи", "São Tomé and Príncipe"),
	("🇸🇦", "SA", "Саудовская Аравия", "Saudi Arabia"),
	("🇸🇿", "SZ", "Эсватини", "Eswatini"),
	("🇸🇨", "SC", "Сейшелы", "Seychelles"),
	("🇸🇳", "SN", "Сенегал", "Senegal"),
	("🇷🇸", "RS", "Сербия", "Serbia"),
	("🇸🇬", "SG", "Сингапур", "Singapore"),
	("🇸🇾", "SY", "Сирия", "Syria"),
	("🇸🇰", "SK", "Словакия", "Slovakia"),
	("🇸🇮", "SI", "Словения", "Slovenia"),
	("🇸🇧", "SB", "Соломоновы Острова", "Solomon Islands"),
	("🇸🇴", "SO", "Сомали", "Somalia"),
	("🇸🇩", "SD", "Судан", "Sudan"),
	("🇸🇷", "SR", "Суринам", "Suriname"),
	("🇺🇸", "US", "США", "United States"),
	("🇸🇱", "SL", "Сьерра-Леоне", "Sierra Leone"),
	("🇹🇯", "TJ", "Таджикистан", "Tajikistan"),
	("🇹🇭", "TH", "Таиланд", "Thailand"),
	("🇹🇿", "TZ", "Танзания", "Tanzania"),
	("🇹🇬", "TG", "Того", "Togo"),
	("🇹🇴", "TO", "Тонга", "Tonga"),
	("🇹🇹", "TT", "Тринидад и Тобаго", "Trinidad and Tobago"),
	("🇹🇻", "TV", "Тувалу", "Tuvalu"),
	("🇹🇳", "TN", "Тунис", "Tunisia"),
	("🇹🇲", "TM", "Туркменистан", "Turkmenistan"),
	("🇹🇷", "TR", "Турция", "Turkey"),
	("🇺🇬", "UG", "Уганда", "Uganda"),
	("🇺🇿", "UZ", "Узбекистан", "Uzbekistan"),
	("🇺🇦", "UA", "Украина", "Ukraine"),
	("🇺🇾", "UY", "Уругвай", "Uruguay"),
	("🇫🇲", "FM", "Микронезия", "Micronesia"),
	("🇫🇯", "FJ", "Фиджи", "Fiji"),
	("🇵🇭", "PH", "Филиппины", "Philippines"),
	("🇫🇮", "FI", "Финляндия", "Finland"),
	("🇫🇷", "FR", "Франция", "France"),
	("🇭🇷", "HR", "Хорватия", "Croatia"),
	("🇨🇫", "CF", "ЦАР", "Central African Republic"),
	("🇹🇩", "TD", "Чад", "Chad"),
	("🇲🇪", "ME", "Черногория", "Montenegro"),
	("🇨🇿", "CZ", "Чехия", "Czech Republic"),
	("🇨🇱", "CL", "Чили", "Chile"),
	("🇨🇭", "CH", "Швейцария", "Switzerland"),
	("🇸🇪", "SE", "Швеция", "Sweden"),
	("🇱🇰", "LK", "Шри-Ланка", "Sri Lanka"),
	("🇪🇨", "EC", "Эквадор", "Ecuador"),
	("🇬🇶", "GQ", "Экваториальная Гвинея", "Equatorial Guinea"),
	("🇪🇷", "ER", "Эритрея", "Eritrea"),
	("🇪🇪", "EE", "Эстония", "Estonia"),
	("🇪🇹", "ET", "Эфиопия", "Ethiopia"),
	("🇿🇦", "ZA", "ЮАР", "South Africa"),
	("🇸🇸", "SS", "Южный Судан", "South Sudan"),
	("🇯🇲", "JM", "Ямайка", "Jamaica"),
	("🇯🇵", "JP", "Япония", "Japan"),
],
"currency": [
	("$", "USD", "Доллар США", "US Dollar"),
	("€", "EUR", "Евро", "Euro"),
	("£", "GBP", "Фунт стерлингов", "Pound Sterling"),
	("¥", "JPY", "Иена / Юань", "Yen / Yuan"),
	("₽", "RUB", "Российский рубль", "Russian Ruble"),
	("₴", "UAH", "Украинская гривна", "Ukrainian Hryvnia"),
	("₸", "KZT", "Казахстанский тенге", "Kazakhstani Tenge"),
	("₿", "BTC", "Биткоин", "Bitcoin"),
	("₹", "INR", "Индийская рупия", "Indian Rupee"),
	("₩", "KRW", "Южнокорейская вона", "South Korean Won"),
	("₪", "ILS", "Израильский шекель", "Israeli Shekel"),
	("₺", "TRY", "Турецкая лира", "Turkish Lira"),
	("₫", "VND", "Вьетнамский донг", "Vietnamese Dong"),
	("₱", "PHP", "Филиппинское песо", "Philippine Peso"),
	("฿", "THB", "Тайский бат", "Thai Baht"),
	("₦", "NGN", "Нигерийская найра", "Nigerian Naira"),
	("₲", "PYG", "Парагвайский гуарани", "Paraguayan Guarani"),
	("₡", "CRC", "Коста-риканский колон", "Costa Rican Colón"),
],
"degrees": [
	("°", "—", "градус", "degree"),
	("°C", "C", "Цельсий", "Celsius"),
	("°F", "F", "Фаренгейт", "Fahrenheit"),
	("K", "K", "Кельвин", "Kelvin"),
	("°R", "R", "Ранкин", "Rankine"),
	("°Ré", "Ré", "Реомюр", "Réaumur"),
	("°Ra", "Ra", "Рёмер", "Rømer"),
	("°D", "D", "Делиль", "Delisle"),
	("°N", "N", "Ньютон", "Newton"),
],
"sizes": [
	("m", "m", "метр", "meter"),
	("km", "km", "километр", "kilometer"),
	("cm", "cm", "сантиметр", "centimeter"),
	("mm", "mm", "миллиметр", "millimeter"),
	("μm", "µm", "микрометр", "micrometer"),
	("nm", "nm", "нанометр", "nanometer"),
	("ft", "ft", "фут", "foot"),
	("in", "in", "дюйм", "inch"),
	("yd", "yd", "ярд", "yard"),
	("mi", "mi", "миля", "mile"),
	("nmi", "nmi", "морская миля", "nautical mile"),
	("kg", "kg", "килограмм", "kilogram"),
	("g", "g", "грамм", "gram"),
	("mg", "mg", "миллиграмм", "milligram"),
	("t", "t", "тонна", "tonne"),
	("lb", "lb", "фунт", "pound"),
	("oz", "oz", "унция", "ounce"),
	("L", "L", "литр", "liter"),
	("mL", "mL", "миллилитр", "milliliter"),
	("m³", "m³", "кубометр", "cubic meter"),
	("ha", "ha", "гектар", "hectare"),
],
"math": [
	("+", "+", "плюс", "plus"),
	("-", "-", "минус", "minus"),
	("×", "*", "умножить", "multiply"),
	("÷", "/", "разделить", "divide"),
	("=", "=", "равно", "equals"),
	("≠", "!=", "не равно", "not equal"),
	("≈", "~=", "приблизительно", "approximately"),
	("≡", "===", "тождественно", "identical"),
	("≤", "<=", "меньше или равно", "less or equal"),
	("≥", ">=", "больше или равно", "greater or equal"),
	("<", "<", "меньше", "less than"),
	(">", ">", "больше", "greater than"),
	("∞", "inf", "бесконечность", "infinity"),
	("√", "sqrt", "корень", "square root"),
	("∑", "sum", "сумма", "sum"),
	("∏", "prod", "произведение", "product"),
	("∫", "int", "интеграл", "integral"),
	("∂", "d/dx", "частная производная", "partial derivative"),
	("π", "pi", "пи", "pi"),
	("∆", "delta", "дельта", "delta"),
	("±", "+-", "плюс-минус", "plus-minus"),
	("∇", "nabla", "набла (градиент)", "nabla (gradient)"),
	("∇²", "laplacian", "лапласиан", "laplacian"),
	("∅", "empty", "пустое множество", "empty 	set"),
	("∈", "in", "принадлежит", "element of"),
	("∉", "not in", "не принадлежит", "not element of"),
	("⊂", "subset", "подмножество", "subset"),
	("⊃", "superset", "надмножество", "superset"),
	("∪", "union", "объединение", "union"),
	("∩", "intersect", "пересечение", "intersection"),
	("∀", "forall", "для всех", "for all"),
	("∃", "exists", "существует", "exists"),
	("¬", "not", "не", "not"),
	("∧", "and", "и", "and"),
	("∨", "or", "или", "or"),
	("→", "->", "импликация", "implication"),
	("↔", "<->", "эквивалентность", "equivalence"),
],
"physics": [
	("Ω", "Ohm", "Ом", "Ohm"),
	("A", "A", "Ампер", "Ampere"),
	("V", "V", "Вольт", "Volt"),
	("W", "W", "Ватт", "Watt"),
	("Hz", "Hz", "Герц", "Hertz"),
	("N", "N", "Ньютон", "Newton"),
	("J", "J", "Джоуль", "Joule"),
	("Pa", "Pa", "Паскаль", "Pascal"),
	("bar", "bar", "Бар", "Bar"),
	("atm", "atm", "Атмосфера", "Atmosphere"),
	("C", "C", "Кулон", "Coulomb"),
	("F", "F", "Фарад", "Farad"),
	("H", "H", "Генри", "Henry"),
	("T", "T", "Тесла", "Tesla"),
	("Wb", "Wb", "Вебер", "Weber"),
	("Sv", "Sv", "Зиверт", "Sievert"),
	("Gy", "Gy", "Грей", "Gray"),
	("Bq", "Bq", "Беккерель", "Becquerel"),
],
"roman": [
	("I", "1", "один", "one"),
	("V", "5", "пять", "five"),
	("X", "10", "десять", "ten"),
	("L", "50", "пятьдесят", "fifty"),
	("C", "100", "сто", "hundred"),
	("D", "500", "пятьсот", "five hundred"),
	("M", "1000", "тысяча", "thousand"),
],
"greek": [
	("α", "alpha", "альфа", "alpha"),
	("β", "beta", "бета", "beta"),
	("γ", "gamma", "гамма", "gamma"),
	("δ", "delta", "дельта", "delta"),
	("ε", "epsilon", "эпсилон", "epsilon"),
	("ζ", "zeta", "зета", "zeta"),
	("η", "eta", "эта", "eta"),
	("θ", "theta", "тета", "theta"),
	("ι", "iota", "йота", "iota"),
	("κ", "kappa", "каппа", "kappa"),
	("λ", "lambda", "лямбда", "lambda"),
	("μ", "mu", "мю", "mu"),
	("ν", "nu", "ню", "nu"),
	("ξ", "xi", "кси", "xi"),
	("ο", "omicron", "омикрон", "omicron"),
	("π", "pi", "пи", "pi"),
	("ρ", "rho", "ро", "rho"),
	("σ", "sigma", "сигма", "sigma"),
	("τ", "tau", "тау", "tau"),
	("υ", "upsilon", "ипсилон", "upsilon"),
	("φ", "phi", "фи", "phi"),
	("χ", "chi", "хи", "chi"),
	("ψ", "psi", "пси", "psi"),
	("ω", "omega", "омега", "omega"),
],
"arrows": [
	("→", "->", "вправо", "right"),
	("←", "<-", "влево", "left"),
	("↑", "^", "вверх", "up"),
	("↓", "v", "вниз", "down"),
	("↔", "<->", "влево-вправо", "left-right"),
	("⇄", "<=>", "туда-сюда", "both ways"),
	("⇒", "=>", "следует", "implies"),
	("⇐", "<=", "обратно", "reverse implies"),
	("⇔", "<=>", "эквивалентно", "equivalent"),
	("↩", "return", "возврат", "return"),
	("↪", "forward", "вперёд", "forward"),
],
"elements": [
	("H", "1", "Водород", "Hydrogen"),
	("He", "2", "Гелий", "Helium"),
	("Li", "3", "Литий", "Lithium"),
	("Be", "4", "Бериллий", "Beryllium"),
	("B", "5", "Бор", "Boron"),
	("C", "6", "Углерод", "Carbon"),
	("N", "7", "Азот", "Nitrogen"),
	("O", "8", "Кислород", "Oxygen"),
	("F", "9", "Фтор", "Fluorine"),
	("Ne", "10", "Неон", "Neon"),
	("Na", "11", "Натрий", "Sodium"),
	("Mg", "12", "Магний", "Magnesium"),
	("Al", "13", "Алюминий", "Aluminium"),
	("Si", "14", "Кремний", "Silicon"),
	("P", "15", "Фосфор", "Phosphorus"),
	("S", "16", "Сера", "Sulfur"),
	("Cl", "17", "Хлор", "Chlorine"),
	("Ar", "18", "Аргон", "Argon"),
	("K", "19", "Калий", "Potassium"),
	("Ca", "20", "Кальций", "Calcium"),
	("Sc", "21", "Скандий", "Scandium"),
	("Ti", "22", "Титан", "Titanium"),
	("V", "23", "Ванадий", "Vanadium"),
	("Cr", "24", "Хром", "Chromium"),
	("Mn", "25", "Марганец", "Manganese"),
	("Fe", "26", "Железо", "Iron"),
	("Co", "27", "Кобальт", "Cobalt"),
	("Ni", "28", "Никель", "Nickel"),
	("Cu", "29", "Медь", "Copper"),
	("Zn", "30", "Цинк", "Zinc"),
	("Ga", "31", "Галлий", "Gallium"),
	("Ge", "32", "Германий", "Germanium"),
	("As", "33", "Мышьяк", "Arsenic"),
	("Se", "34", "Селен", "Selenium"),
	("Br", "35", "Бром", "Bromine"),
	("Kr", "36", "Криптон", "Krypton"),
	("Rb", "37", "Рубидий", "Rubidium"),
	("Sr", "38", "Стронций", "Strontium"),
	("Y", "39", "Иттрий", "Yttrium"),
	("Zr", "40", "Цирконий", "Zirconium"),
	("Nb", "41", "Ниобий", "Niobium"),
	("Mo", "42", "Молибден", "Molybdenum"),
	("Tc", "43", "Технеций", "Technetium"),
	("Ru", "44", "Рутений", "Ruthenium"),
	("Rh", "45", "Родий", "Rhodium"),
	("Pd", "46", "Палладий", "Palladium"),
	("Ag", "47", "Серебро", "Silver"),
	("Cd", "48", "Кадмий", "Cadmium"),
	("In", "49", "Индий", "Indium"),
	("Sn", "50", "Олово", "Tin"),
	("Sb", "51", "Сурьма", "Antimony"),
	("Te", "52", "Теллур", "Tellurium"),
	("I", "53", "Иод", "Iodine"),
	("Xe", "54", "Ксенон", "Xenon"),
	("Cs", "55", "Цезий", "Caesium"),
	("Ba", "56", "Барий", "Barium"),
	("La", "57", "Лантан", "Lanthanum"),
	("Ce", "58", "Церий", "Cerium"),
	("Pr", "59", "Празеодим", "Praseodymium"),
	("Nd", "60", "Неодим", "Neodymium"),
	("Pm", "61", "Прометий", "Promethium"),
	("Sm", "62", "Самарий", "Samarium"),
	("Eu", "63", "Европий", "Europium"),
	("Gd", "64", "Гадолиний", "Gadolinium"),
	("Tb", "65", "Тербий", "Terbium"),
	("Dy", "66", "Диспрозий", "Dysprosium"),
	("Ho", "67", "Гольмий", "Holmium"),
	("Er", "68", "Эрбий", "Erbium"),
	("Tm", "69", "Тулий", "Thulium"),
	("Yb", "70", "Иттербий", "Ytterbium"),
	("Lu", "71", "Лютеций", "Lutetium"),
	("Hf", "72", "Гафний", "Hafnium"),
	("Ta", "73", "Тантал", "Tantalum"),
	("W", "74", "Вольфрам", "Tungsten"),
	("Re", "75", "Рений", "Rhenium"),
	("Os", "76", "Осмий", "Osmium"),
	("Ir", "77", "Иридий", "Iridium"),
	("Pt", "78", "Платина", "Platinum"),
	("Au", "79", "Золото", "Gold"),
	("Hg", "80", "Ртуть", "Mercury"),
	("Tl", "81", "Таллий", "Thallium"),
	("Pb", "82", "Свинец", "Lead"),
	("Bi", "83", "Висмут", "Bismuth"),
	("Po", "84", "Полоний", "Polonium"),
	("At", "85", "Астат", "Astatine"),
	("Rn", "86", "Радон", "Radon"),
	("Fr", "87", "Франций", "Francium"),
	("Ra", "88", "Радий", "Radium"),
	("Ac", "89", "Актиний", "Actinium"),
	("Th", "90", "Торий", "Thorium"),
	("Pa", "91", "Протактиний", "Protactinium"),
	("U", "92", "Уран", "Uranium"),
	("Np", "93", "Нептуний", "Neptunium"),
	("Pu", "94", "Плутоний", "Plutonium"),
	("Am", "95", "Америций", "Americium"),
	("Cm", "96", "Кюрий", "Curium"),
	("Bk", "97", "Берклий", "Berkelium"),
	("Cf", "98", "Калифорний", "Californium"),
	("Es", "99", "Эйнштейний", "Einsteinium"),
	("Fm", "100", "Фермий", "Fermium"),
	("Md", "101", "Менделевий", "Mendelevium"),
	("No", "102", "Нобелий", "Nobelium"),
	("Lr", "103", "Лоуренсий", "Lawrencium"),
	("Rf", "104", "Резерфордий", "Rutherfordium"),
	("Db", "105", "Дубний", "Dubnium"),
	("Sg", "106", "Сиборгий", "Seaborgium"),
	("Bh", "107", "Борий", "Bohrium"),
	("Hs", "108", "Хассий", "Hassium"),
	("Mt", "109", "Мейтнерий", "Meitnerium"),
	("Ds", "110", "Дармштадтий", "Darmstadtium"),
	("Rg", "111", "Рентгений", "Roentgenium"),
	("Cn", "112", "Коперниций", "Copernicium"),
	("Nh", "113", "Нихоний", "Nihonium"),
	("Fl", "114", "Флеровий", "Flerovium"),
	("Mc", "115", "Московий", "Moscovium"),
	("Lv", "116", "Ливерморий", "Livermorium"),
	("Ts", "117", "Теннессин", "Tennessine"),
	("Og", "118", "Оганесон", "Oganesson"),
],
}

def handle(command):
	parts = command.split(maxsplit=2)
	cmd = parts[0]
	arg = parts[1] if len(parts) > 1 else ""
	lang = parts[2] if len(parts) > 2 else "ru"

	if cmd == "qlist":
		if not arg:
			print("\033[1mqlist — Quick List:\033[0m")
			print("  \033[36mqlist countries\033[0m — страны")
			print("  \033[36mqlist all\033[0m       — всё сразу")
			print("")
			print("\033[1mЯзыки:\033[0m  ru (по умолчанию) | en | both")
			return

		if arg == "all":
			for section, items in DATA.items():
				print("\n\033[1m── " + section + " ──\033[0m")
				for item in items:
					symbol, code, name_ru, name_en = item
					if lang == "en":
						print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_en)
					elif lang == "both":
						print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_ru + " / " + name_en)
					else:
						print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_ru)
			return

		if arg in DATA:
			print("\033[1m── " + arg + " ──\033[0m")
			for item in DATA[arg]:
				symbol, code, name_ru, name_en = item
				if lang == "en":
					print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_en)
				elif lang == "both":
					print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_ru + " / " + name_en)
				else:
					print("  \033[33m" + symbol.ljust(5) + "\033[0m" + code.ljust(12) + name_ru)
